import { SummaryData, MSAData } from "../types";

export const MOCK_SUMMARY_DATA: SummaryData = {
  msaOverview: {
    totalMSAs: 384,
    totalBanks: 4125,
  },
  targetedOpportunities: {
    highAttractiveMSAs: 42,
    excellentOpportunities: 15,
    opportunityDistribution: {
      "High": 15,
      "Medium": 45,
      "Low": 40
    }
  },
  nationalMarket: {
    totalMarketSize: 18500000,
    avgRiskScore: 45.2,
    avgPricing: 102.5,
    avgLendingVolumeChange: 5.4,
    avgLoanToDepositChange: -2.1,
  },
  riskPricing: {
    premiumMarkets: 120,
    atParMarkets: 150,
    discountMarkets: 114,
    rationalPricing: 200,
    irrationalPricing: 184,
    overpricedOpportunity: 50,
    underpricedRisk: 30,
  },
};

export const MOCK_MAP_DATA: MSAData[] = [
  {
    MSA: "New York-Newark-Jersey City, NY-NJ-PA",
    Product: "Commercial Real Estate",
    LAT: 40.7128,
    LON: -74.0060,
    Attractiveness_Score: 85,
    Attractiveness_Category: "High",
    "Market Size": 5000000,
    Risk: 40,
    Price: 105,
    Driving_Metric: "Market Size",
    Market_Size_Score: "High",
    HHI_Score: "Medium",
    Economic_Growth_Score: "High",
    Loan_Growth_Score: "Medium",
    Risk_Score: "Low",
    Risk_Migration_Score: "Stable",
    Relative_Risk_Migration_Score: "Stable",
    Premium_Discount_Score: "Premium",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "High",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Pricing aligns with risk profile",
  },
  {
    MSA: "Los Angeles-Long Beach-Anaheim, CA",
    Product: "Commercial Real Estate",
    LAT: 34.0522,
    LON: -118.2437,
    Attractiveness_Score: 82,
    Attractiveness_Category: "High",
    "Market Size": 3500000,
    Risk: 45,
    Price: 104,
    Driving_Metric: "Market Size",
    Market_Size_Score: "High",
    HHI_Score: "Low",
    Economic_Growth_Score: "High",
    Loan_Growth_Score: "High",
    Risk_Score: "Medium",
    Risk_Migration_Score: "Improving",
    Relative_Risk_Migration_Score: "Positive",
    Premium_Discount_Score: "Premium",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "High",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Strong demand supports pricing",
  },
  {
    MSA: "Chicago-Naperville-Elgin, IL-IN-WI",
    Product: "Commercial Real Estate",
    LAT: 41.8781,
    LON: -87.6298,
    Attractiveness_Score: 75,
    Attractiveness_Category: "Medium",
    "Market Size": 2800000,
    Risk: 55,
    Price: 101,
    Driving_Metric: "Risk",
    Market_Size_Score: "High",
    HHI_Score: "Medium",
    Economic_Growth_Score: "Medium",
    Loan_Growth_Score: "Low",
    Risk_Score: "High",
    Risk_Migration_Score: "Stable",
    Relative_Risk_Migration_Score: "Neutral",
    Premium_Discount_Score: "At Par",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "Medium",
    International_CM_Score: "Medium",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Pricing reflects economic conditions",
  },
  {
    MSA: "Dallas-Fort Worth-Arlington, TX",
    Product: "Commercial Real Estate",
    LAT: 32.7767,
    LON: -96.7970,
    Attractiveness_Score: 88,
    Attractiveness_Category: "High",
    "Market Size": 2500000,
    Risk: 35,
    Price: 103,
    Driving_Metric: "Economic Growth",
    Market_Size_Score: "High",
    HHI_Score: "Low",
    Economic_Growth_Score: "Very High",
    Loan_Growth_Score: "High",
    Risk_Score: "Low",
    Risk_Migration_Score: "Improving",
    Relative_Risk_Migration_Score: "Positive",
    Premium_Discount_Score: "Premium",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "Medium",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "High growth justifies premium",
  },
  {
    MSA: "Houston-The Woodlands-Sugar Land, TX",
    Product: "Commercial Real Estate",
    LAT: 29.7604,
    LON: -95.3698,
    Attractiveness_Score: 78,
    Attractiveness_Category: "Medium",
    "Market Size": 2200000,
    Risk: 50,
    Price: 102,
    Driving_Metric: "Market Size",
    Market_Size_Score: "High",
    HHI_Score: "Medium",
    Economic_Growth_Score: "High",
    Loan_Growth_Score: "Medium",
    Risk_Score: "Medium",
    Risk_Migration_Score: "Stable",
    Relative_Risk_Migration_Score: "Neutral",
    Premium_Discount_Score: "At Par",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "Medium",
    International_CM_Score: "High",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Balanced market dynamics",
  },
  {
    MSA: "Miami-Fort Lauderdale-West Palm Beach, FL",
    Product: "Commercial Real Estate",
    LAT: 25.7617,
    LON: -80.1918,
    Attractiveness_Score: 84,
    Attractiveness_Category: "High",
    "Market Size": 2000000,
    Risk: 42,
    Price: 106,
    Driving_Metric: "Price",
    Market_Size_Score: "High",
    HHI_Score: "Low",
    Economic_Growth_Score: "High",
    Loan_Growth_Score: "High",
    Risk_Score: "Medium",
    Risk_Migration_Score: "Improving",
    Relative_Risk_Migration_Score: "Positive",
    Premium_Discount_Score: "Premium",
    Pricing_Rationality_Score: "Irrational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "High",
    Pricing_Rationality: "Irrational",
    Pricing_Rationality_Explanation: "Pricing exceeds fundamental value",
  },
  {
    MSA: "Austin-Round Rock, TX",
    Product: "Commercial Real Estate",
    LAT: 30.2672,
    LON: -97.7431,
    Attractiveness_Score: 90,
    Attractiveness_Category: "High",
    "Market Size": 1200000,
    Risk: 30,
    Price: 104,
    Driving_Metric: "Growth",
    Market_Size_Score: "Medium",
    HHI_Score: "Low",
    Economic_Growth_Score: "Very High",
    Loan_Growth_Score: "Very High",
    Risk_Score: "Low",
    Risk_Migration_Score: "Improving",
    Relative_Risk_Migration_Score: "Positive",
    Premium_Discount_Score: "Premium",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "Low",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Strong fundamentals",
  },
  {
    MSA: "San Francisco-Oakland-Hayward, CA",
    Product: "Commercial Real Estate",
    LAT: 37.7749,
    LON: -122.4194,
    Attractiveness_Score: 70,
    Attractiveness_Category: "Medium",
    "Market Size": 2400000,
    Risk: 60,
    Price: 98,
    Driving_Metric: "Risk",
    Market_Size_Score: "High",
    HHI_Score: "High",
    Economic_Growth_Score: "Low",
    Loan_Growth_Score: "Low",
    Risk_Score: "High",
    Risk_Migration_Score: "Deteriorating",
    Relative_Risk_Migration_Score: "Negative",
    Premium_Discount_Score: "Discount",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "High",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Correction in progress",
  },
  {
    MSA: "Seattle-Tacoma-Bellevue, WA",
    Product: "Commercial Real Estate",
    LAT: 47.6062,
    LON: -122.3321,
    Attractiveness_Score: 76,
    Attractiveness_Category: "Medium",
    "Market Size": 1800000,
    Risk: 48,
    Price: 100,
    Driving_Metric: "Tech",
    Market_Size_Score: "High",
    HHI_Score: "High",
    Economic_Growth_Score: "Medium",
    Loan_Growth_Score: "Medium",
    Risk_Score: "Medium",
    Risk_Migration_Score: "Stable",
    Relative_Risk_Migration_Score: "Neutral",
    Premium_Discount_Score: "At Par",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "High",
    International_CM_Score: "Medium",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Market stabilizing",
  },
  {
    MSA: "Atlanta-Sandy Springs-Roswell, GA",
    Product: "Commercial Real Estate",
    LAT: 33.7490,
    LON: -84.3880,
    Attractiveness_Score: 81,
    Attractiveness_Category: "High",
    "Market Size": 1900000,
    Risk: 45,
    Price: 101,
    Driving_Metric: "Growth",
    Market_Size_Score: "High",
    HHI_Score: "Medium",
    Economic_Growth_Score: "High",
    Loan_Growth_Score: "High",
    Risk_Score: "Medium",
    Risk_Migration_Score: "Stable",
    Relative_Risk_Migration_Score: "Neutral",
    Premium_Discount_Score: "At Par",
    Pricing_Rationality_Score: "Rational",
    Revenue_per_Company_Score: "Medium",
    International_CM_Score: "Medium",
    Pricing_Rationality: "Rational",
    Pricing_Rationality_Explanation: "Good balance",
  }
];