/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "khxiymbfpsadihkgicul"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeGl5bWJmcHNhZGloa2dpY3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MTkxNjksImV4cCI6MjA3NTA5NTE2OX0.c6-LH4iiZIJ1EKqWkrLFij-1n58aEy2_PjlU0qzNPzM"